properties([
    parameters([
        string(name: 'repoUrl', defaultValue: '', description: 'give github repo url to build'),
        string(name: 'branchName', defaultValue: 'master', description: 'give github repo branch to build')
    ])
])
node {

    stage('Git Checkout') {
       git (
                url: "${repoUrl}",
                branch: "${branchName}"
            )
    }
}
